import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'

import type { Languages } from '@/hooks/i18n'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { lang: Languages }
}) {
  const { lang } = params
  return (
    <html lang={lang}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
